# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1785e8eb1588d3eae358e0e99b83270cd5236c77273621d4b74d2e90a60704360a17c749333a1b0a25ffa8d2c5515bac950e243182dbeb5fe98ff63a060da372

test:
  secret_key_base: d28b2a84547e0b4628b6a9711688cece7c4a955f1a8155809ee295a25d0b50d649607bdce6ac69c8c6d1cfc87e5eb278ea2a8820a00b460e9a860cfc8e9161b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
